<?php
    session_start();
    require_once('config.inc.php');
    $id=$_SESSION['ID'];
    
    $conn_str = DB_SYS.':host='.DB_HOST.';dbname='.DB_NAME;
    try
    {
       
        $pdo = new PDO($conn_str,DB_USER,DB_PASS);
        $lpdo = new PDO($conn_str,DB_USER,DB_PASS);
        $name="";
        $age=0;
        $profile="";
        $matric=0;
        $inter=0;
        $bachelor=0;
        $master=0;
        $phd=0;
        $language_i="";
        $language_ii="";
        $language_iii="";
        $objective_i="";
        $objective_ii="";
        $objective_iii="";
        $experience_i="";
        $experience_ii="";
        $experience_iii="";
        $skills_i="";
        $skills_ii="";
        $skills_iii="";
        $hobbies_i="";
        $hobbies_ii="";
        $hobbies_iii="";
        $reference_i="";
        $reference_ii="";
        $reference_iii="";
        $address="";
        $email="";
        $phone="";
        if(isset($_POST))
        {
            if(isset($_POST['nname']))
                {
                    $name=$_POST['nname'];
                }
            else
                {
                    $name=NULL;
                }
            if(isset($_POST['age']))
                {
                    $age=$_POST['age'];
                }
            else
                {
                    $age=0;
                }
                if(isset($_POST['matric']))
                {
                    $matric=$_POST['matric'];
                }
            else
                {
                    $matric=0;
                }
            if(isset($_POST['inter']))
                {
                    $inter=$_POST['inter'];
                }
            else
                {
                    $inter=0;
                }
            if(isset($_POST['bachelor']))
                {
                    $bachelor=$_POST['bachelor'];
                }
            else
                {
                    $bachelor=0;
                }            
            if(isset($_POST['master']))
                {
                    $master=$_POST['master'];
                }
            else
                {
                    $master=0;
                }              
            if(isset($_POST['phd']))
                {
                    $phd=$_POST['phd'];
                }
            else
                {
                    $phd=0;
                }
                
            if(isset($_POST['profile']))
                {
                    $profile=$_POST['profile'];
                }
            else
                {
                    $profile=NULL;
                }
            
                if(isset($_POST['language_i']))
                {
                    $language_i=$_POST['language_i'];
                }
            else
                {
                    $language_i=NULL;
                }
            if(isset($_POST['language_ii']))
                {
                    $language_ii=$_POST['language_ii'];
                }
            else
                {
                    $language_ii=NULL;
                }
            if(isset($_POST['language_iii']))
                {
                    $language_iii=$_POST['language_iii'];
                }
            else
                {
                    $language_iii=NULL;
                }  
                if(isset($_POST['objective_i']))
                {
                    $objective_i=$_POST['objective_i'];
                }
            else
                {
                    $objective_i=NULL;
                }
            if(isset($_POST['objective_ii']))
                {
                    $objective_ii=$_POST['objective_ii'];
                }
            else
                {
                    $objective_ii=NULL;
                }
            if(isset($_POST['objective_iii']))
                {
                    $objective_iii=$_POST['objective_iii'];
                }
            else
                {
                    $objective_iii=NULL;
                }     
                if(isset($_POST['experience_i']))
                {
                    $experience_i=$_POST['experience_i'];
                }
            else
                {
                    $experience_i=NULL;
                }
            if(isset($_POST['experience_ii']))
                {
                    $experience_ii=$_POST['experience_ii'];
                }
            else
                {
                    $experience_ii=NULL;
                }
            if(isset($_POST['experience_iii']))
                {
                    $experience_iii=$_POST['experience_iii'];
                }
            else
                {
                    $experience_iii=NULL;
                }                      
                if(isset($_POST['skills_i']))
                {
                    $skills_i=$_POST['skills_i'];
                }
            else
                {
                    $skills_i=NULL;
                }
            if(isset($_POST['skills_ii']))
                {
                    $skills_ii=$_POST['skills_ii'];
                }
            else
                {
                    $skills_ii=NULL;
                }
            if(isset($_POST['skills_iii']))
                {
                    $skills_iii=$_POST['skills_iii'];
                }
            else
                {
                    $skills_iii=NULL;
                } 

                if(isset($_POST['hobbies_i']))
                {
                    $hobbies_i=$_POST['hobbies_i'];
                }
            else
                {
                    $hobbies_i=NULL;
                }
            if(isset($_POST['hobbies_ii']))
                {
                    $hobbies_ii=$_POST['hobbies_ii'];
                }
            else
                {
                    $hobbies_ii=NULL;
                }
            if(isset($_POST['hobbies_iii']))
                {
                    $hobbies_iii=$_POST['hobbies_iii'];
                }
            else
                {
                    $hobbies_iii=NULL;
                } 
                if(isset($_POST['reference_i']))
                {
                    $reference_i=$_POST['reference_i'];
                }
            else
                {
                    $reference_i=NULL;
                }
            if(isset($_POST['reference_ii']))
                {
                    $reference_ii=$_POST['reference_ii'];
                }
            else
                {
                    $reference_ii=NULL;
                }
            if(isset($_POST['reference_iii']))
                {
                    $reference_iii=$_POST['reference_iii'];
                }
            else
                {
                    $reference_iii=NULL;
                }  
             if(isset($_POST['cellno']))
                {
                    $phone=$_POST['cellno'];
                }
            else
                {
                    
                    echo"Phone NH";
                    die();
                }             
            if(isset($_POST['address']))
                {
                    $address=$_POST['address'];
                }
            else
                {
                    $address=NULL;
                    
                } 
            if(isset($_POST['email']))
                {
                    $email=$_POST['email'];
                }
            else
                {
                    $email=NULL;
                    
                }
                
        }
        $nsql="INSERT INTO homepagedata (ID,Name,Age,Matric,Inter,Bachelor,Master,PHD,Profile,
        Language_1,Language_2,Language_3,
        Objective_1,Objective_2,Objective_3,
        Experience_1,Experience_2,Experience_3,
        Skills_1,Skills_2,Skills_3,
        Hobbies_1,Hobbies_2,Hobbies_3,
        Reference_1,Reference_2,Reference_3,Address,Email,Phone
        ) VALUES('".$id."','".$name."',".$age.",".$matric.",".$inter.",".$bachelor.",".$master.",".$phd.",'".$profile."',
        '".$language_i."','".$language_ii."','".$language_iii."',
        '".$objective_i."','".$objective_ii."','".$objective_iii."',
        '".$experience_i."','".$experience_ii."','".$experience_iii."',
        '".$skills_i."','".$skills_ii."','".$skills_iii."',
        '".$hobbies_i."','".$hobbies_i."','".$hobbies_iii."',
        '".$reference_i."','".$reference_ii."','".$reference_iii."','".$address."','".$email."','".$phone."')";
          $pdo->exec($nsql);
        header("Location:showlogin_user.php?id=".$id."",true,302);
        
    
            }catch(PDOException $e)
            {
                die('Server error');
            }
            ?>
        